services:
  go:
    image: barito-be:latest
    build: ../.
    ports:
      - 8090:8090
    env_file:
      - .env
    command: >
      bash -c "
        ./wait-for-it.sh -t 0 db:3306 -- \
        make migration-migrate USERNAME=testing PASSWORD=12345678 HOST=db PORT=3306 DATABASE=test_db \
        /app/bin
      "
    depends_on:
      - db
  
  db:
    image: mysql:8.0.40-debian
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'testing'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - 3307:3306
    command: mysqld --default-authentication-plugin=mysql_native_password

  venom:
    image: barito-venom:latest
    build:
      dockerfile: venom.Dockerfile
    volumes:
      - ./tests:/workdir/tests
      - ./results:/workdir/results
    command: >
      bash -c "
        ./wait-for-it.sh -t 0 go:8090 -- \
        mysql --user=testing --password=12345678 -h db -P 3306 test_db < seeds.sql \
        /usr/local/venom run ./tests/*.y*ml
      "
    depends_on:
      - go
