openapi: 3.0.1
info:
  title: Orders
  version: 0.0.1
tags:
  - name: Orders
paths:
  /v1/orders:
    post:
      operationId: createOrder
      tags:
        - Orders
      summary: create a new order
      description: create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        201:
          description: order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        404:
          description: user is not found or books are not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    NewOrder:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 1
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
      required:
        - userId
        - items
    Item:
      type: object
      properties:
        bookId:
          type: integer
          format: int64
          example: 1
        qty:
          type: integer
          example: 1
      required:
        - bookId
        - qty
    CreateOrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
      required:
        - id
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: an unexpected error occured
      required:
        - message
